version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: droopie-nocobase_server_1
      APP_PORT: 80

  server:
    image: nocobase/nocobase:latest-full
    restart: on-failure
    environment:
      - APP_KEY=6dab6dc3f86631bb3962cd8854211d0df71fe361631d52ae9e10c60133bce9af
    volumes:
      - nocobase_storage:/app/nocobase/storage

volumes:
  nocobase_storage:
