version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: droopie-plane_web_1
      APP_PORT: 3000

  web:
    image: makeplane/plane-frontend:latest
    restart: on-failure
    environment:
      - NEXT_PUBLIC_API_BASE_URL=/api
