version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: droopie-deerflow_server_1
      APP_PORT: 8000

  server:
    image: bytedance/deer-flow:latest
    restart: on-failure
    environment:
      - PORT=8000
