version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: droopie-crawl4ai_server_1
      APP_PORT: 11235

  server:
    image: unclecode/crawl4ai:latest
    restart: on-failure
    volumes:
      - /dev/shm:/dev/shm
