version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: droopie-crawl4ai_server_1
      APP_PORT: 8000

  server:
    image: unclecode/crawl4ai:latest
    restart: on-failure
    environment:
      - PORT=8000
